[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# 1) API → backend (works over HTTP because Netlify does the proxy server-side)
[[redirects]]
  from = "/api/*"
  to = "http://75.119.151.238:5001/:splat"
  status = 200
  force = true

# 2) SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200